//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frackhubsignup9.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
   

    public partial class User
    {

        [Required(ErrorMessage = "please enter the user name", AllowEmptyStrings = false)]
        public string name { get; set; }
        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0 - 9a - zA - Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$", ErrorMessage="please provide valid email")]

        public string email { get; set; }
        [Required(ErrorMessage = "please enter the password", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50,MinimumLength =8, ErrorMessage ="password must be 8 characters long")]
        public string password { get; set; }

        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]

        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "please enter the phonenumber", AllowEmptyStrings = false)]
        public string phone_number { get; set; }
        [Required(ErrorMessage = "please enter the brp number", AllowEmptyStrings = false)]
        public string brp_number { get; set; }
        [Required(ErrorMessage = "please enter the date of birth", AllowEmptyStrings = false)]
        public System.DateTime date_of_birth { get; set; }
    }
}
